<?php

namespace AppBundle\Repository;

/**
 * Aimer_phraseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Aimer_phraseRepository extends \Doctrine\ORM\EntityRepository
{
}
