<?php

namespace AppBundle\Repository;

/**
 * AimerPhraseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AimerPhraseRepository extends \Doctrine\ORM\EntityRepository
{
}
