<?php

namespace AppBundle\Repository;

/**
 * Droit_GroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Droit_GroupeRepository extends \Doctrine\ORM\EntityRepository
{
}
