<?php

namespace AppBundle\Repository;

/**
 * droit_membreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class droit_membreRepository extends \Doctrine\ORM\EntityRepository
{
}
