<?php

namespace AppBundle\Repository;

/**
 * Enum_type_objetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Enum_type_objetRepository extends \Doctrine\ORM\EntityRepository
{
}
