<?php

namespace AppBundle\Repository;

/**
 * Enum_categorie_jugementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Enum_categorie_jugementRepository extends \Doctrine\ORM\EntityRepository
{
}
