<?php

namespace AppBundle\Repository;

/**
 * Enum_poids_reponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Enum_poids_reponseRepository extends \Doctrine\ORM\EntityRepository
{
}
