<?php

namespace AppBundle\Repository;

/**
 * Enum_type_succesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Enum_type_succesRepository extends \Doctrine\ORM\EntityRepository
{
}
