<?php

namespace AppBundle\Repository;

/**
 * Enum_voteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Enum_voteRepository extends \Doctrine\ORM\EntityRepository
{
}
