<?php

namespace AppBundle\Repository;

/**
 * Glose_mot_ambiguRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Glose_mot_ambiguRepository extends \Doctrine\ORM\EntityRepository
{
}
