<?php

namespace AppBundle\Repository;

/**
 * GloseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GloseRepository extends \Doctrine\ORM\EntityRepository
{
}
