<?php

namespace AppBundle\Repository;

/**
 * JAimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JAimeRepository extends \Doctrine\ORM\EntityRepository
{
}
