<?php

namespace AppBundle\Repository;

/**
 * jugementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class jugementRepository extends \Doctrine\ORM\EntityRepository
{
}
