<?php

namespace AppBundle\Repository;

/**
 * Mot_ambigu_phraseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Mot_ambigu_phraseRepository extends \Doctrine\ORM\EntityRepository
{
}
