<?php

namespace AppBundle\Repository;

/**
 * Mot_ambiguRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Mot_ambiguRepository extends \Doctrine\ORM\EntityRepository
{
}
