<?php

namespace AppBundle\Repository;

/**
 * SuccesMembreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuccesMembreRepository extends \Doctrine\ORM\EntityRepository
{
}
