<?php

namespace AppBundle\Repository;

/**
 * VisiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisiteRepository extends \Doctrine\ORM\EntityRepository
{
	public function checkVisite()
	{
		$visite = new \AppBundle\Entity\Visite();
		$hoursBetween2Visites = 24;

		$lastVisite = $this->createQueryBuilder('v')
			->where("v.ip = :ip")->setParameter("ip", $visite->getIp())
			->andWhere("v.userAgent = :userAgent")->setParameter("userAgent", $visite->getUserAgent())
			->orderBy("v.dateVisite", 'DESC')
			->setMaxResults(1)
			->getQuery()->getOneOrNullResult();

		if($lastVisite == null){
			$date1 = $lastVisite->getDateVisite()->getTimestamp();
			$date2 = $visite->getDateVisite()->getTimestamp();
			$hours = ($date2 - $date1) / 3600;

			if($hours >= $hoursBetween2Visites){
				$em = $this->_em;
				$em->persist($visite);
				$em->flush();
			}
		}
	}
}
