<?php

namespace AppBundle\Repository;

/**
 * VisiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisiteRepository extends \Doctrine\ORM\EntityRepository
{
	public function checkVisite()
	{
		$visite = new \AppBundle\Entity\Visite();
		$hoursBetween2Visites = 24;

		$lastVisite = $this->createQueryBuilder('v')
			->where("v.ip = :ip")->setParameter("ip", $visite->getIp())
			->andWhere("v.userAgent = :userAgent")->setParameter("userAgent", $visite->getUserAgent())
			->orderBy("v.dateVisite", 'DESC')
			->setMaxResults(1)
			->getQuery()->getOneOrNullResult();

		$hours = null;
		if($lastVisite != null){
			$date1 = $lastVisite->getDateVisite()->getTimestamp();
			$date2 = $visite->getDateVisite()->getTimestamp();
			$hours = ($date2 - $date1) / 3600;
		}

		if($lastVisite == null || $hours >= $hoursBetween2Visites){
			$em = $this->_em;
			$em->persist($visite);
			$em->flush();
		}
	}

	public function getStat()
	{
		$array = array();

		$array['total'] = $this->createQueryBuilder('v')
			                  ->select('count(v) total')
			                  ->getQuery()->getSingleResult()['total'];

		$dateJ30 = new \DateTime();
		$dateJ30->setTimestamp($dateJ30->getTimestamp() - (3600 * 24 * 30));
		$array['j30'] = $this->createQueryBuilder('v')
			                ->select('count(v) j30')
			                ->where('v.dateVisite > :j30')->setParameter('j30', $dateJ30)
			                ->getQuery()->getSingleResult()['j30'];

		$dateJ7 = new \DateTime();
		$dateJ7->setTimestamp($dateJ7->getTimestamp() - (3600 * 24 * 7));
		$array['j7'] = $this->createQueryBuilder('v')
			               ->select('count(v) j7')
			               ->where('v.dateVisite > :j7')->setParameter('j7', $dateJ7)
			               ->getQuery()->getSingleResult()['j7'];

		$dateH24 = new \DateTime();
		$dateH24->setTimestamp($dateH24->getTimestamp() - (3600 * 24));
		$array['h24'] = $this->createQueryBuilder('v')
			                ->select('count(v) h24')
			                ->where('v.dateVisite > :h24')->setParameter('h24', $dateH24)
			                ->getQuery()->getSingleResult()['h24'];

		return $array;
	}
}
