<?php

namespace AppBundle\Repository;

/**
 * VoteJugementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteJugementRepository extends \Doctrine\ORM\EntityRepository
{
}
