<?php

namespace AppBundle\Repository;

/**
 * vote_jugementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class vote_jugementRepository extends \Doctrine\ORM\EntityRepository
{
}
