imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: admin.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    site_name: "Ambiguss"
    version: "1.2.0"
    # Phrase
    costCreatePhraseByMotAmbiguCredits: 100
    gainCreatePhrasePoints: 25
    gainPerLikePhrasePoints: 25
    gainPercentByGame: 10
    dureeAvantJouabiliteSecondes: 300
    nbPhrasesDisponiblesNonConnecte: 25
    # Glose
    costCreateGloseByGlosesOfMotAmbigu: 50
    # Classement
    maxResultForClassementGeneral: 100
    maxResultForClassementPhrases: 100
    # Jugement
    dureeDeliberationSecondes: 432000 # 5 jours
    # Emails contact
    emailContact: "alexdu98@gmx.fr"
    # Email from
    emailFrom: "noreply@ambiguss.fr"
    # Visite
    timeBetweenTwoVisitesSecondes: 86400 # 1 jour
    # Download directory of export
    downloadDirectory: "%kernel.project_dir%/web/download/"
    # Infos of export
    infosExport: >
        Données collectées depuis le jeu Ambiguss.
        Site web réalisé en 2017 dans le cadre d'un TER de première année de master informatique à l'université de Montpellier.
        Groupe : Isna Ouazi, Melissa Mekaoui, Nicolas Delalande, Alexandre Culty.
        Tuteur : Mathieu Lafourcade.
    # Durée avant expiration des cookies d'aide
    ttl_cookie_helper: 60 # jours
    ttl_cookie_info: 365 # jours

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.project_dir%/app/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments:       ~
    http_method_override: true
    assets:
        version: "%version%"
        version_format: '%%s?v=%%s'
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'bootstrap_3_layout.html.twig'
    globals:
        costCreatePhraseByMotAmbiguCredits: "%costCreatePhraseByMotAmbiguCredits%"
        gainCreatePhrasePoints: "%gainCreatePhrasePoints%"
        gainPerLikePhrasePoints: "%gainPerLikePhrasePoints%"
        gainPercentByGame: "%gainPercentByGame%"
        costCreateGloseByGlosesOfMotAmbigu: "%costCreateGloseByGlosesOfMotAmbigu%"
        recaptcha: "%recaptcha%"
        version: "%version%"
        ttl_cookie_helper: "%ttl_cookie_helper%"
        ttl_cookie_info: "%ttl_cookie_info%"
        nbPhrasesDisponiblesNonConnecte: "%nbPhrasesDisponiblesNonConnecte%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            datetime_functions:
                DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat
        
# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\Membre
    service:
        mailer: AppBundle\Service\MailerService
    group:
        group_class: AppBundle\Entity\Groupe
        form:
            type: AppBundle\Form\FOSUser\GroupeType
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    registration:
        confirmation:
            enabled: true
        form:
            type: AppBundle\Form\FOSUser\RegistrationType
            validation_groups: ~
    profile:
        form:
            type: AppBundle\Form\FOSUser\ProfilEditType
            validation_groups: ~
    change_password:
        form:
            type: AppBundle\Form\FOSUser\ChangePasswordType
            validation_groups: ~
    resetting:
        form:
            type: AppBundle\Form\FOSUser\ResettingType
            validation_groups: ~

hwi_oauth:
    connect:
        confirmation: true
        account_connector: fos_user.registration.form.factory
    firewall_names: [main]
    resource_owners:
        facebook:
            type: facebook
            client_id: "%facebook_id%"
            client_secret: "%facebook_secret%"
            options:
                display: popup
                csrf: true
            scope: "email"
        twitter:
            type: twitter
            client_id: "%twitter_id%"
            client_secret: "%twitter_secret%"
            options:
                display: popup
                csrf: true
                include_email: true
            scope: "email"
        google:
            type: google
            client_id: "%google_id%"
            client_secret: "%google_secret%"
            options:
                display: popup
                csrf: true
            scope: "email"
    fosub:
        username_iterations: 30
        properties:
            facebook: facebookId
            twitter: twitterId
            google: googleId

doctrine_migrations:
    dir_name: "%kernel.project_dir%/migrations"
    namespace: AppBundle\Migrations
    table_name: migrations
    name: Application Migrations
    organize_migrations: false
    all_or_nothing: true

sensio_framework_extra:
    router:
        annotations: false
