imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AppBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    # Phrase
    costCreatePhraseByMotAmbiguCredits: 100
    gainCreatePhrasePoints: 25
    gainPerLikePhrasePoints: 25
    gainPercentByGame: 10
    dureeAvantJouabiliteSecondes: 300
    # Glose
    costCreateGloseByGlosesOfMotAmbigu: 50
    # Classement
    maxResultForClassementGeneral: 100
    maxResultForClassementPhrases: 100
    # Jugement
    dureeDeliberationSecondes: 432000 # 5 jours
    # Emails contact
    emailContact: "alexdu98@gmx.fr"
    # Email from
    emailFrom: "noreply@ambiguss.fr"
    # Visite
    timeBetweenTwoVisitesSecondes: 86400 # 1 jour
    # Download directory
    downloadDirectory: "%kernel.project_dir%/web/download/"
    # Recaptcha key
    recaptcha: "6LcXBhkUAAAAAIMfOvKJODxXAhw-qG2VzGG2rppj"
    recaptchaKey: "6LcXBhkUAAAAAOXVtSYLei5DUOfYh1ZEfsIhz0yv"

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.project_dir%/app/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'bootstrap_3_layout.html.twig'
    globals:
        costCreatePhraseByMotAmbiguCredits: "%costCreatePhraseByMotAmbiguCredits%"
        gainCreatePhrasePoints: "%gainCreatePhrasePoints%"
        gainPerLikePhrasePoints: "%gainPerLikePhrasePoints%"
        gainPercentByGame: "%gainPercentByGame%"
        costCreateGloseByGlosesOfMotAmbigu: "%costCreateGloseByGlosesOfMotAmbigu%"
        recaptcha: "%recaptcha%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        
# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\Membre
    service:
        mailer: AppBundle\Service\Mailer
    group:
        group_class: AppBundle\Entity\Groupe
        form:
            type: AppBundle\Form\GroupeType
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    registration:
        confirmation:
            enabled: true
        form:
            type: AppBundle\Form\RegistrationType
    profile:
        form:
            type: AppBundle\Form\ProfilEditType
    change_password:
        form:
            type: AppBundle\Form\ChangePasswordType
    resetting:
        form:
            type: AppBundle\Form\ResettingType