app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@AppBundle/Resources/config/FOSUser_routing.yml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"