hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

twitter_login:
    path: /login/check-twitter

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

comment:
    resource: "@CommentBundle/Resources/config/routing.yml"
    prefix:   /

judgment:
    resource: "@JudgmentBundle/Resources/config/routing.yml"
    prefix:   /

ambiguss:
    resource: "@AmbigussBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"