ambiguss:
    resource: "@AmbigussBundle/Resources/config/routing.yml"
    prefix:   /

connexion:
    path: /connexion
    defaults:
        _controller: UserBundle:Security:connexion

connexion_verif:
    path: /connexion_verif

deconnexion:
    path: /deconnexion