administration:
    resource: "@AdministrationBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

judgment:
    resource: "@JudgmentBundle/Resources/config/routing.yml"
    prefix:   /

ambiguss:
    resource: "@AmbigussBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"