ambiguss:
    resource: "@AmbigussBundle/Resources/config/routing.yml"
    prefix:   /

inscription:
    path: /inscription
    defaults:
        _controller: UserBundle:Security:inscription

connexion:
    path: /connexion
    defaults:
        _controller: UserBundle:Security:connexion

connexion_verif:
    path: /connexion_verif

deconnexion:
    path: /deconnexion