security:
  encoders:
    Symfony\Component\Security\Core\User\User:
      algorithm: bcrypt
      cost: 10
    UserBundle\Entity\Membre:
      algorithm: bcrypt
      cost: 10

  role_hierarchy:
    ROLE_MEMBRE:          ROLE_VISITEUR
    ROLE_MODERATEUR:      ROLE_MEMBRE
    ROLE_ADMINISTRATEUR:  ROLE_MODERATEUR

  providers:
    webservice:
      id: user.membre_provider

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern: ^/
      anonymous: true
      provider:     webservice
      remember_me:
        secret: '%secret%'
        lifetime: 604800 # 7 jours
        path: /
        name: jeton
        remember_me_parameter: 'userbundle_membre[KeepCo]'
      logout_on_user_change: true
      form_login:
        login_path: /connexion
        check_path: /connexion/verification
        username_parameter: userbundle_membre[Pseudo]
        password_parameter: userbundle_membre[Mdp]
      logout:
        path:       /deconnexion
        target:     /
    # A mettre avant le main pour HWI
    secured_area:
      anonymous: ~
      logout_on_user_change: true

  access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
    - { path: ^/admin, roles: ROLE_ADMINISTRATEUR }
