security:
  encoders:
    Symfony\Component\Security\Core\User\User:
      algorithm: bcrypt
      cost: 10
    UserBundle\Entity\Membre:
      algorithm: bcrypt
      cost: 10

  role_hierarchy:
    ROLE_MEMBRE:          ROLE_VISITEUR
    ROLE_MODERATEUR:      ROLE_MEMBRE
    ROLE_ADMINISTRATEUR:  ROLE_MODERATEUR

  providers:
    main:
      entity:
        class: UserBundle\Entity\Membre
        property: pseudo

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern: ^/
      anonymous: true
      provider:     main
      remember_me:
        secret: '%secret%'
        lifetime: 604800 # 7 jours
        path: /
        name: jeton
        remember_me_parameter: 'userbundle_membre[KeepCo]'
      form_login:
        login_path: /connexion
        check_path: /connexion/verification
        username_parameter: userbundle_membre[Pseudo]
        password_parameter: userbundle_membre[Mdp]
      logout:
        path:       /deconnexion
        target:     /

  access_control:
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
