security:
  encoders:
    FOS\UserBundle\Model\UserInterface: bcrypt

  providers:
    fos_userbundle:
      id: fos_user.user_provider.username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern: ^/
      anonymous: true
      remember_me:
        secret: '%secret%'
        lifetime: 604800 # 7 jours
        path: /
        name: jeton
      logout_on_user_change: true
      form_login:
        provider: fos_userbundle
        login_path: fos_user_security_login
        failure_path: fos_user_security_login
        check_path: fos_user_security_check
        default_target_path: app_accueil
        csrf_token_generator: security.csrf.token_manager
        use_referer: true
      logout:
        path: fos_user_security_logout
        target: fos_user_security_login
      oauth:
        resource_owners:
          facebook: "/login/check-facebook"
          twitter: "/login/check-twitter"
          google: "/login/check-google"
        login_path: /connexion
        failure_path: /connexion
        use_forward: false
        oauth_user_provider:
          service: AppBundle\Service\FOSUserProvider

  access_control:
    - { path: ^/connexion$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/deconnexion$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/inscription, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/reinitialisation, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/, role: ROLE_ADMINISTRATEUR }
