security:
  encoders:
    Symfony\Component\Security\Core\User\User:
      algorithm: bcrypt
      cost: 10
    AmbigussBundle\Entity\Membre:
      algorithm: bcrypt
      cost: 10

  role_hierarchy:
    ROLE_MEMBRE:          ROLE_VISITEUR
    ROLE_MODERATEUR:      ROLE_MEMBRE
    ROLE_ADMINISTRATEUR:  ROLE_MODERATEUR

  providers:
    main:
      entity:
        class: AmbigussBundle\Entity\Membre
        property: pseudo

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern: ^/
      anonymous: true
      provider:     main
      form_login:
        login_path: connexion
        check_path: connexion_verif
      logout:
        path:       deconnexion
        target:     /

  access_control:
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
