services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    Symfony\Component\Security\Core\Authorization\Voter\RoleHierarchyVoter:
        arguments: { $roleHierarchy: "@security.role_hierarchy" }
        tags:
            - { name: security.voter }

    AppBundle\Service\ExportService:
        autowire: true
        arguments: { $infos: '%infosExport%', $downloadDir: '%downloadDirectory%' }

    AppBundle\Service\RecaptchaService:
        autowire: true
        arguments: { $secret: '%recaptcha_secret%' }

    security.role_hierarchy:
        autowire: true
        class: 'AppBundle\Service\RoleHierarchyService'

    AppBundle\Service\FOSUserProvider:
        autowire: true
        arguments:
            $properties:
                facebook: 'facebook'
                twitter: 'twitter'
                google: 'google'

    # Pour surcharger le UserChecker de HWI
    security.user_checker:
        class: AppBundle\Service\UserChecker
