services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    AppBundle\Form\RegistrationType:
        tags:
            - { name: form.type, alias: app_user_registration }

    AppBundle\Form\ProfilEditType:
        tags:
            - { name: form.type, alias: app_user_profile }

    AppBundle\Form\ChangePasswordType:
        tags:
            - { name: form.type, alias: app_user_change_password }

    AppBundle\Form\ResettingType:
        tags:
            - { name: form.type, alias: app_user_resetting }

    AppBundle\Form\GroupType:
        tags:
            - { name: form.type, alias: app_user_group }

    Symfony\Component\Security\Core\Authorization\Voter\RoleHierarchyVoter:
        arguments: { $roleHierarchy: "@security.role_hierarchy" }
        tags:
            - { name: security.voter }