ambiguss_phrase_view:
    path: /ambiguss/phrase/view/{id}
    defaults:
        _controller: AmbigussBundle:Phrase:view
    requirements:
        id: \d+

ambiguss_phrase_add:
    path: /ambiguss/phrase/add
    defaults: {_controller: AmbigussBundle:Phrase:add }

ambiguss_phrase_edit:
    path: /ambiguss/phrase/edit/{id}
    defaults:
        _controller: AmbigussBundle:Phrase:edit
    requirements:
        id: \d+

ambiguss_phrase_delete:
    path: /ambiguss/phrase/delete/{id}
    defaults:
        _controller: AmbigussBundle:Phrase:delete
    requirements:
        id: \d+
    options:
        expose: true

ambiguss_game_result:
    path: /ambiguss/jeu/resultat
    defaults:
        _controller: AmbigussBundle:Game:resultat

ambiguss_game:
    path: /ambiguss/jeu/{id}
    defaults:
        {_controller: AmbigussBundle:Game:main,id: null}

ambiguss_glose_get_autocomplete:
    path: /ambiguss/glose/get/autocomplete
    defaults:
        _controller: AmbigussBundle:API:autocompleteGlose
    options:
        expose: true

ambiguss_glose_add:
    path: /ambiguss/glose/add
    defaults:
        _controller: AmbigussBundle:API:addGlose

ambiguss_glose_edit:
    path: /ambiguss/glose/edit/{id}
    defaults:
        _controller: AmbigussBundle:Glose:editGlose
        id: null

ambiguss_glose_delete:
    path: /ambiguss/glose/delete/{id}
    defaults:
        _controller: AmbigussBundle:Glose:deleteGlose
    requirements:
        id: \d+
    options:
        expose: true

ambiguss_glose_link:
    path: /ambiguss/glose/link/{id}
    defaults:
        _controller: AmbigussBundle:Glose:linkGlose
    requirements:
        id: \d+
    options:
        expose: true

ambiguss_glose_get_by_motambigu:
    path: /ambiguss/glose/getByMotAmbigu
    defaults:
        _controller: AmbigussBundle:API:getGlosesByMotAmbigu
    options:
        expose: true

ambiguss_classement_general:
    path: /ambiguss/classement/general
    defaults:
        _controller: AmbigussBundle:Classement:classementGeneral

ambiguss_classement_personnel:
    path: /ambiguss/classement/personnel
    defaults:
        _controller: AmbigussBundle:Classement:classementPersonnel

ambiguss_classement_phrases:
    path: /ambiguss/classement/phrases
    defaults:
        _controller: AmbigussBundle:Classement:classementPhrases

ambiguss_phrase_like:
    path: /ambiguss/phrase/like/{id}
    defaults:
        _controller: AmbigussBundle:Phrase:like
    requirements:
        id: \d+

ambiguss_phrase_signal:
    path: /ambiguss/phrase/signal/{id}
    defaults:
        _controller: AmbigussBundle:Phrase:signal
    requirements:
        id: \d+

ambiguss_export:
    path: /ambiguss/export
    defaults:
        _controller: AmbigussBundle:Export:main

ambiguss_gloses:
    path: /ambiguss/gloses
    defaults:
        _controller: AmbigussBundle:Glose:main

ambiguss_moderation_phrase:
    path: /ambiguss/moderation/phrases
    defaults:
        _controller: AmbigussBundle:Phrase:moderation

ambiguss_moderation_ma:
    path: /ambiguss/moderation/mots_ambigus
    defaults:
        _controller: AmbigussBundle:MotAmbigu:moderation_ma

ambiguss_motambigu_keep:
    path: /ambiguss/motambigu/keep/{id}
    defaults:
        _controller: AmbigussBundle:MotAmbigu:keep
    requirements:
        id: \d+
    options:
        expose: true

ambiguss_phrase_keep:
    path: /ambiguss/phrase/keep/{id}
    defaults:
        _controller: AmbigussBundle:Phrase:keep
    requirements:
        id: \d+
    options:
        expose: true