ambiguss_phrase:
    path: /ambiguss/phrase
    defaults: {_controller: AmbigussBundle:Phrase:main }

ambiguss_phrase_view:
    path: /ambiguss/phrase/view/{id}
    defaults:
        _controller: AmbigussBundle:Phrase:view
    requirements:
        id: \d+

ambiguss_phrase_add:
    path: /ambiguss/phrase/add
    defaults: {_controller: AmbigussBundle:Phrase:add }

ambiguss_phrase_edit:
    path: /ambiguss/phrase/edit/{id}
    defaults:
        _controller: AmbigussBundle:Phrase:edit
    requirements:
            id: \d+

ambiguss_phrase_delete:
    path: /ambiguss/phrase/delete{id}
    defaults:
        _controller: AmbigussBundle:Phrase:delete
    requirements:
            id: \d+

ambiguss_game:
    path: /ambiguss/jeu
    defaults:
        _controller: AmbigussBundle:Game:main

ambiguss_glose_add:
    path: /ambiguss/glose/add
    defaults:
        _controller: AmbigussBundle:API:addGlose