ambiguss_accueil:
    path:     /
    defaults: { _controller: AmbigussBundle:Accueil:main }

ambiguss_mentions:
    path:     /mentions
    defaults: { _controller: AmbigussBundle:Mentions:main }

ambiguss_conditions:
    path:     /conditions
    defaults: { _controller: AmbigussBundle:Conditions:main }

ambiguss_contact:
    path:     /contact
    defaults: { _controller: AmbigussBundle:Contact:main }

creationPhrase:
    path: /creationPhrase
    defaults: {_controller: AmbigussBundle:CreationPhrase:main }