services:
    ambiguss.phraseHTML:
        class: AmbigussBundle\Services\Phrase
        tags:
            - { name: twig.extension }
    ambiguss_export:
        class: AmbigussBundle\Controller\ExportController