judgment_homepage:
    path: /jugement
    defaults:
        _controller: JudgmentBundle:Main:index

jugement_add:
    path: /jugement/add
    defaults:
        _controller: JudgmentBundle:API:addJugement