<?php

namespace UserBundle\Repository;

/**
 * MembreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembreRepository extends \Doctrine\ORM\EntityRepository
{
	public function findOneByPseudoOrEmail($pseudoOrEmail){
		return $this->createQueryBuilder('m')
			->where("m.pseudo = :pseudo")->setParameter("pseudo", $pseudoOrEmail)
			->orWhere("m.email = :email")->setParameter("email", $pseudoOrEmail)
			->getQuery()->getOneOrNullResult();
	}
}
