<?php

namespace UserBundle\Repository;

/**
 * TypeSuccesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeSuccesRepository extends \Doctrine\ORM\EntityRepository
{
}
