<?php

namespace JudgmentBundle\Repository;

/**
 * CategorieJugementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieJugementRepository extends \Doctrine\ORM\EntityRepository
{
}
