user_inscription:
    path: /inscription
    defaults:
        _controller: UserBundle:Security:inscription

user_inscription_provider:
    path: /inscription/{provider}
    defaults:
        _controller: UserBundle:Security:inscription
    requirements:
        provider: "[a-z]*"
    options:
        expose: true

user_inscription_confirmation:
    path: /inscription/confirmation/{cle}
    defaults:
        _controller: UserBundle:Security:inscriptionConfirmation
    requirements:
        cle: "[a-z0-9]+"

user_connexion:
    path: /connexion
    defaults:
        _controller: UserBundle:Security:connexion

user_connexion_verification:
    path: /connexion/verification

user_deconnexion:
    path: /deconnexion

user_oubli_mdp:
    path: /oubli-mdp
    defaults:
        _controller: UserBundle:Security:oubliMdp