user_inscription:
    path: /inscription
    defaults:
        _controller: UserBundle:Security:inscription

user_inscription_provider:
    path: /inscription/{provider}
    defaults:
        _controller: UserBundle:Security:inscription
    requirements:
        provider: "[a-z]*"
    options:
        expose: true

user_inscription_confirmation:
    path: /inscription/confirmation/{cleOubliMdp}
    defaults:
        _controller: UserBundle:Security:inscriptionConfirmation
    requirements:
        cle: "[a-zA-Z0-9]+"

user_connexion:
    path: /connexion
    defaults:
        _controller: UserBundle:Security:connexion

user_connexion_verification:
    path: /connexion/verification

user_deconnexion:
    path: /deconnexion

user_oubli_mdp:
    path: /oubli-mdp
    defaults:
        _controller: UserBundle:Security:oubliMdp

user_oubli_mdp_reinitialisation:
    path: /oubli-mdp/reinitialisation/{cleOubliMdp}
    defaults:
        _controller: UserBundle:Security:oubliMdpReinitialisation
    requirements:
        cle: "[a-zA-Z0-9]+"

user_modif_profil:
    path: /modifier
    defaults:
        _controller: UserBundle:Utilisateur:ModifProfil

user_profil:
    path: /user/profil/{id}
    defaults:
        {_controller: UserBundle:Utilisateur:Profil, id : null}
    options:
        expose: true

user_get_pseudo_email:
    path: /membre/pseudoEmail
    defaults:
        _controller: UserBundle:API:getMembreByPseudoOrEmail