services:
    user.security.authentification.success:
        class: UserBundle\Listeners\AuthentificationListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onAuthentificationSuccess }