fos_user_security_login:
    path: /connexion
    controller: fos_user.security.controller:loginAction
    methods: [GET, POST]

fos_user_security_check:
    path: /login_check
    controller: fos_user.security.controller:checkAction
    methods: [POST]

fos_user_security_logout:
    path: /deconnexion
    controller: fos_user.security.controller:logoutAction
    methods: [GET, POST]

fos_user_profile_show:
    path: /profil/{id}
    controller: AppBundle:User:show
    methods: [GET]
    defaults:
        id: null
    options:
        expose: true

fos_user_profile_edit:
    path: /profil/edit
    controller: fos_user.profile.controller:editAction
    methods: [GET, POST]

fos_user_change_password:
    path: /profil/edit/password
    controller: fos_user.change_password.controller:changePasswordAction
    methods: [GET, POST]

fos_user_registration_register:
    path: /inscription/
    controller: fos_user.registration.controller:registerAction
    methods: [GET, POST]

fos_user_registration_check_email:
    path: /inscription/check-email
    controller: fos_user.registration.controller:checkEmailAction
    methods: [GET]

fos_user_registration_confirm:
    path: /inscription/confirmation/{token}
    controller: fos_user.registration.controller:confirmAction
    methods: [GET]

fos_user_registration_confirmed:
    path: /inscription/confirme"
    controller: fos_user.registration.controller:confirmedAction
    methods: [GET]

fos_user_resetting_request:
    path: /reinitialisation/
    controller: fos_user.resetting.controller:requestAction
    methods: [GET]

fos_user_resetting_send_email:
    path: /reinitialisation/send-email
    controller: fos_user.resetting.controller:sendEmailAction
    methods: [POST]

fos_user_resetting_check_email:
    path: /reinitialisation/check-email
    controller: fos_user.resetting.controller:checkEmailAction
    methods: [GET]

fos_user_resetting_reset:
    path: /reinitialisation/reset/{token}
    controller: fos_user.resetting.controller:resetAction
    methods: [GET, POST]

fos_user_group_list:
    path: /group/list
    controller: fos_user.group.controller:listAction
    methods: [GET]

fos_user_group_new:
    path: /group/new
    controller: fos_user.group.controller:newAction
    methods: [GET, POST]

fos_user_group_show:
    path: /group/{groupName}
    controller: fos_user.group.controller:showAction
    methods: [GET]

fos_user_group_edit:
    path: /group/{groupName}/edit
    controller: fos_user.group.controller:editAction
    methods: [GET, POST]

fos_user_group_list:
    path: /group/list
    controller: fos_user.group.controller:listAction
    methods: [GET]