app_accueil:
    path:     /
    defaults: { _controller: AppBundle:Main:accueil }

app_mentions:
    path:     /mentions
    defaults: { _controller: AppBundle:Main:mentions }

app_conditions:
    path:     /conditions
    defaults: { _controller: AppBundle:Main:conditions }

app_contact:
    path:     /contact
    defaults: { _controller: AppBundle:Main:contact }

app_apropos:
    path:     /a-propos
    defaults: { _controller: AppBundle:Main:aPropos }