services:

    AppBundle\Service\Export:
        autowire: true
        arguments: { $downloadDir: "%downloadDirectory%" }

    AppBundle\Service\Recaptcha:
        autowire: true
        arguments: { $key: "%recaptchaKey%" }

    security.role_hierarchy:
        autowire: true
        class: AppBundle\Service\RoleHierarchy