services:

    AppBundle\Service\ExportService:
        autowire: true
        arguments: { $downloadDir: "%downloadDirectory%" }

    AppBundle\Service\Recaptcha:
        autowire: true
        arguments: { $secret: "%recaptcha_secret%" }

    security.role_hierarchy:
        autowire: true
        class: AppBundle\Service\RoleHierarchy

    AppBundle\Service\FOSUserProvider:
        autowire: true
        arguments:
            $properties:
                facebook: facebook
                twitter: twitter
                google: google
