services:
    app.recaptcha:
        class: AppBundle\Services\Recaptcha
    app.twig.visite:
        class: AppBundle\Services\Visite
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - {name: twig.extension}