services:

    AppBundle\Service\Visite:
        autowire: true
        arguments: { $timeBetweenTwoVisites: "%timeBetweenTwoVisitesSecondes%" }

    AppBundle\Service\Export:
        autowire: true
        arguments: { $downloadDir: "%downloadDirectory%" }