<?php

namespace AmbigussBundle\Repository;

/**
 * DroitGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DroitGroupeRepository extends \Doctrine\ORM\EntityRepository
{
}
