<?php

namespace AmbigussBundle\Repository;

/**
 * DroitMembreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DroitMembreRepository extends \Doctrine\ORM\EntityRepository
{
}
