<?php

namespace AmbigussBundle\Repository;

/**
 * GloseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GloseRepository extends \Doctrine\ORM\EntityRepository
{
	public function findGlosesValueByMotAmbiguValue($valeurMA){
		return $this->createQueryBuilder('g')->select('g.id, g.valeur')
			->innerJoin("g.motsAmbigus", "ma", "WITH", "ma.valeur = :valeurMA")->setParameter('valeurMA', $valeurMA)
			->orderBy("g.valeur")
			->getQuery()->getResult();
	}

	public function findByValeurAutoComplete($valeur){
		return $this->createQueryBuilder('g')->select('g.valeur')
			->where('g.valeur LIKE :valeur')->setParameter('valeur', $valeur . '%')
			->getQuery()->getResult();
	}

	public function findOneOrCreate($glose)
	{
		$entity = $this->findOneByValeur($glose->getValeur());
		if($entity == null){
			$this->_em->persist($glose);
			$this->_em->flush();
			return $glose;
		}
		return $entity;
	}
}
