<?php

namespace AmbigussBundle\Repository;

/**
 * JugementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JugementRepository extends \Doctrine\ORM\EntityRepository
{
}
