<?php

namespace AmbigussBundle\Repository;

/**
 * MotAmbiguSpecialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotAmbiguSpecialRepository extends \Doctrine\ORM\EntityRepository
{
}
