<?php

namespace AmbigussBundle\Repository;

/**
 * MotAmbiguRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotAmbiguRepository extends \Doctrine\ORM\EntityRepository
{
	public function findOneOrCreate($motAmbigu)
	{
		$entity = $this->findOneByValeur($motAmbigu->getValeur());
		if($entity == null){
			$this->_em->persist($motAmbigu);
			$this->_em->flush();
			return $motAmbigu;
		}
		return $entity;
	}

	public function findByValeurAutoComplete($valeur)
	{
		return $this->createQueryBuilder('ma')->select('ma.valeur')
			->where('ma.valeur LIKE :valeur')->setParameter('valeur', $valeur . '%')
			->getQuery()->getResult();
	}

    public function getSignale()
    {
        return $this->createQueryBuilder('g')
            ->innerJoin('g.auteur', 'a', 'WITH', 'g.auteur = a.id')->addSelect('a')
            ->leftJoin('g.modificateur', 'm', 'WITH', 'g.modificateur = m.id')->addSelect('m')
            ->where('g.signale = 1')
            ->andWhere('g.visible=1')
            ->getQuery()->getResult();
    }

	public function getStat()
	{
		$array = array();

		$array['total'] = $this->createQueryBuilder('ma')
			                  ->select('count(ma) total')
			                  ->getQuery()->getSingleResult()['total'];

		$dateJ7 = new \DateTime();
		$dateJ7->setTimestamp($dateJ7->getTimestamp() - (3600 * 24 * 7));
		$array['creationJ7'] = $this->createQueryBuilder('ma')
			                       ->select('count(ma) creationJ7')
			                       ->where('ma.dateCreation > :j7')->setParameter('j7', $dateJ7)
			                       ->getQuery()->getSingleResult()['creationJ7'];

		$array['signale'] = $this->createQueryBuilder('ma')
			                    ->select('count(ma) signale')
			                    ->where('ma.signale = 1')
			                    ->getQuery()->getSingleResult()['signale'];

		return $array;
	}

}
