<?php

namespace AmbigussBundle\Repository;

/**
 * MotAmbiguRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotAmbiguRepository extends \Doctrine\ORM\EntityRepository
{
}
