<?php

namespace AmbigussBundle\Repository;

/**
 * PartieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartieRepository extends \Doctrine\ORM\EntityRepository
{

	public function countAllGamesByMembre($membre)
	{
		return $this->createQueryBuilder('p')
			->select('count(p) nbParties')
			->where('p.joueur = :membre')->setParameter('membre', $membre)
			->andWhere('p.joue = 1')
			->getQuery()->getSingleResult();
	}
}
