<?php

namespace AmbigussBundle\Repository;

/**
 * PoidsReponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoidsReponseRepository extends \Doctrine\ORM\EntityRepository
{
}
