<?php

namespace AmbigussBundle\Repository;

/**
 * SuccesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuccesRepository extends \Doctrine\ORM\EntityRepository
{
}
