<?php

namespace AmbigussBundle\Repository;

/**
 * TypeDroitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeDroitRepository extends \Doctrine\ORM\EntityRepository
{
}
