<?php

namespace AmbigussBundle\Repository;

/**
 * TypeVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeVoteRepository extends \Doctrine\ORM\EntityRepository
{
}
