<?php

namespace AmbigussBundle\Repository;

/**
 * TypeObjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeObjetRepository extends \Doctrine\ORM\EntityRepository
{
}
