administration_accueil:
    path:     /admin
    defaults: { _controller: AdministrationBundle:Admin:main }

administration_statistiques:
    path:     /admin/statistiques
    defaults: { _controller: AdministrationBundle:Admin:statistiques }

administration_membres:
    path:     /admin/membres
    defaults: { _controller: AdministrationBundle:Admin:membres }

administration_membre_edit:
    path:     /admin/membre/edit/{id}
    defaults: { _controller: AdministrationBundle:Admin:editMembre }
    requirements:
        id: \d+|$

administration_phrases:
    path:     /admin/phrases
    defaults: { _controller: AdministrationBundle:Admin:phrases }

administration_gloses:
    path:     /admin/gloses
    defaults: { _controller: AdministrationBundle:Admin:gloses }