administration_accueil:
    path:     /admin
    defaults: { _controller: AdministrationBundle:Admin:main }

administration_statistiques:
    path:     /admin/statistiques
    defaults: { _controller: AdministrationBundle:Admin:statistiques }